title: kPherox Blog
description: My Notes

paginate: 10
paginate_path: /page/:num

permalink: /:categories/:slug:output_ext
excerpt_separator: <!--more-->

theme: jekyll-theme-primer

lang: ja

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

feed:
  excerpt_only: true
