title: Notes | kpherox[.]dev

url: https://kphrx.github.io
baseurl: /notes

pagination:
  enabled: true
  sort_reverse: true
  per_page: 8
  permalink: page/:num.html

autopages:
  enabled: true
  tags:
    layouts:
      - autopage_tag.html
    title: "Posts tagged with :tag"
    permalink: /tag/:tag
    slugify:
      case: false
  categories:
    layouts:
      - autopage_category.html
    title: "Posts in category :cat"
    permalink: /category/:cat
    slugify:
      case: false
  collections:
    layouts:
      - autopage_collection.html
    title: "Posts in collection :coll"
    permalink: /collection/:coll
    slugify:
      case: false

permalink: /:slug:output_ext
excerpt_separator: <!--more-->

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

lang: ja

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: highlight
    block:
      formatter: HTMLLinewise
      wrap: true
      tag_name: span
      class: line

  footnote_backlink: '&#8617;&#65038;'
  # footnote_backlink: '&#x21A9;&#xFE0E;'

feed:
  posts_limit: 0
  excerpt_only: true
