title: kPherox Blog
description: My Notes

pagination:
  enabled: true
  sort_reverse: true
  per_page: 10
  permalink: /page/:num.html

permalink: /:categories/:title:output_ext
excerpt_separator: <!--more-->

theme: jekyll-theme-primer

lang: ja

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

  footnote_backlink: '&#8617;&#65038;'
  # footnote_backlink: '&#x21A9;&#xFE0E;'

feed:
  excerpt_only: true
