title: kPherox Blog
description: My Notes

pagination:
  enabled: true
  sort_reverse: true
  per_page: 8
  permalink: page/:num.html
  title: ':title'

autopages:
  enabled: true
  tags:
    layouts:
      - autopage.html
    title: Posts tagged with ":tag"
    permalink: /tag/:tag
    slugify:
      case: false
  categories:
    layouts:
      - autopage.html
    title: Posts in category ":cat"
    permalink: /:cat
    slugify:
      case: false
  collections:
    layouts:
      - autopage.html
    title: Posts in collection ":coll"
    permalink: /collection/:coll
    slugify:
      case: false

permalink: /:categories/:title:output_ext
excerpt_separator: <!--more-->

titles_from_headings:
  strip_title: true
  collections: true

theme: jekyll-theme-primer

lang: ja

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

  footnote_backlink: '&#8617;&#65038;'
  # footnote_backlink: '&#x21A9;&#xFE0E;'

feed:
  excerpt_only: true
